### ISSUE TITLE
Add .editorconfig file to the project

### ISSUE THREAD

**Issue by delightedcat** [TheBoneJarmer/TiledCS#10]
As the amount of contributors for this project seems to be growing, I would suggest adding a `.editorconfig` file to the project.  This file is a standard that helps keeping things like line endings, charsets, indents and whitespaces consistent.

It prevents and fixes problems with development across different operating systems and text editor configurations. For more information, check the [.editorconfig home page](https://editorconfig.org/).

Most popular text editors and IDEs support the `.editorconfig` file. For instance, here's the [VS Code extension](https://github.com/editorconfig/editorconfig-vscode) that I'm using that updates my file with the specifications set in the file as soon as I save it.

I have an example of such file in my [dotfiles repository](https://github.com/DelightedCat/dotfiles/blob/main/.editorconfig) which I'm pretty much copy-pasting into new projects I create.

**Comment by TheBoneJarmer** [comment]
I am gonna decline this for the time being. It is true it could be handy but I do not do anything different than Visual Studio's defaults. Usually when I approve someone's pull request I modify their code slightly anyway to fit the overall style because I am too lazy to ask the authors to do so. lol
