### ISSUE TITLE
Support for Base64 tile layers

### ISSUE THREAD

**Issue by foreverWIP** [TheBoneJarmer/TiledCS#12]
Tiled offers the ability to encode tile data as base64 to reduce file size, and even has options for compression to reduce it further. In the past I've often found myself decoding and using these formats in game engine code so large maps could be stored in a much smaller size, and I'd love to see support for it come to this library. I have a fork ready that allows reading most of these base64 formats, this is just a check to see if there's interest in implementing it.

**Comment by TheBoneJarmer** [comment]
Hey @foreverWIP 

Thank you for your kind words, I really appreciate it! As for the base64 compression, it has not been implemented because it was never requested haha. So feel free to open a pull request (do target the **develop** branch please) and I'll have a look at your changes.

With kind regards,
TheBoneJarmer

**Comment by TheBoneJarmer** [comment]
Hi @foreverWIP 

I would like to let you know that I found some time to look at your changes. And they do look really good! I will have to perform some testing here and there to be sure everything keeps working but so far I can tell that you did a really great job. Well done!

With kind regards,
TheBoneJarmer

**Comment by TheBoneJarmer** [comment]
Hi

Sorry for the late reply. I was extremely busy and got sick on top that so even less time. I just now merged your changes. I would like to thank you again for your input.

With kind regards,
TheBoneJarmer
