### ISSUE TITLE
Add support for MonoGame content pipeline

### ISSUE THREAD

**Issue by TheBoneJarmer** [TheBoneJarmer/TiledCS#2]
According to several issues on the repo of TiledSharp, many users of MonoGame like to have a library like this to parse TiledMaps for their game. MonoGame however has its own way of loading assets using the content pipeline. And in order to make TiledCS work with MonoGame, some changes need to be made.

**Comment by DelightedCat** [comment]
As far as I know, at least one requirement to get everything to work with the MonoGame content pipeline would be that the assets that can be loaded using the content pipeline have an empty constructor, so that they can be initialized and loaded as follows:
```cs
TiledMap map = Content.Load<TiledMap>("Path/To/Asset");
```
These types would include `TiledMap` and `TiledTileset`, assuming a separate importer will be used for tileset files.

I'll look into getting the library to work in an example project by setting up a simple DesktopGL project with a custom pipeline extension and propose any changes to the code where required, unless another workflow is preferred.

**Comment by DelightedCat** [comment]
Another thing I just realized: In order to support MonoGame, we'll need to support .NET Standard 2.0. This can be done by building the library for multiple targets by editing the following like in `TiledCS.csproj`:
```xml
<TargetFramework>net5.0</TargetFramework>
```
Into the following for example:
```xml
<TargetFrameworks>net5.0;netstandard2.0</TargetFrameworks>
```
Without this change it's impossible to use this library alongside MonoGame, let alone a custom content pipeline extension.

**Comment by DelightedCat** [comment]
Currently working on an implementation of the library for MonoGame which can be found here: https://github.com/DelightedCat/TiledCS.MonoGame

**Comment by TheBoneJarmer** [comment]
> Another thing I just realized: In order to support MonoGame, we'll need to support .NET Standard 2.0. This can be done by building the library for multiple targets by editing the following like in `TiledCS.csproj`:
> 
> ```
> <TargetFramework>net5.0</TargetFramework>
> ```
> 
> Into the following for example:
> 
> ```
> <TargetFrameworks>net5.0;netstandard2.0</TargetFrameworks>
> ```
> 
> Without this change it's impossible to use this library alongside MonoGame, let alone a custom content pipeline extension.

Now you mention it, I didn't realise it was set to net5.0. I mean, I knew but I was not aware it was not targeting netstandard2.0. As it is just a library we could just replace net5.0 with netstandard2.0. Thanks for clarifying that one out!

**Comment by TheBoneJarmer** [comment]
> Currently working on an implementation of the library for MonoGame which can be found here: https://github.com/DelightedCat/TiledCS.MonoGame

Looks really good so far!
