### ISSUE TITLE
Support for Layer Groups

### ISSUE THREAD

**Issue by TwBurn** [TheBoneJarmer/TiledCS#21]
It seems Groups aren't supported, when I read a (v1.5) TMX file, which has layers in groups, those layers aren't available using `map.Layers`, nor is there a `map.Groups` property.

**Comment by TheBoneJarmer** [comment]
Hi @TwBurn 

You are correct, TiledCS does not support that yet. To be fairly honest, I did not knew about these groups until now. That said, after a short research it seems that supporting groups does not look too difficult to do. Thanks for letting us know. :)

With kind regards,
TheBoneJarmer

**Comment by TheBoneJarmer** [comment]
Hi @TwBurn 

I just pushed NuGet package 2.4.0. This contains support for groups and more. I noticed image layers are also a thing and it seemed like I was missing support for some properties too. Let me know if this works for you.

With kind regards,
TheBoneJarmer

**Comment by TwBurn** [comment]
Thanks, that seems to work!
One small thing, the properties of the TiledGroup seem to start with a lowercase, instead of an uppercase letter. Eg, it's `TiledMap.Layers`, but `TiledGroup.layers` - but I see that there are more objects that have the lowercase convention. Is that on purpose?

**Comment by TheBoneJarmer** [comment]
Yes, it is. Because in C# fields are written in camel case while properties, methods and classes are written in pascal case. And I purposely did not use auto-properties on the models because there was no point to it. :)

**Comment by TheBoneJarmer** [comment]
Ok, forget my previous deleted comment (you probably got mail already so you know what I replied). I misread. It is not on purpose. The TiledMap.Layers should in fact be TiledMap.layers. Well spotted! Will be changed with the next version.

**Comment by TheBoneJarmer** [comment]
Okay, forget it haha. Clearly I need to go to bed because I am mixing things up here. Sooo forget all I said up till now and just stick to this answer: Yes it is on purpose. The TiledMap.Layers is an auto-property, which are written in **PamelCase** by convention. And the fields in the models are well, fields. Those are written in **camelCase** by convention. That is why the difference exist.

That said, I'm signing out now before I confuse the heck out of you even further. That said, since things work for you I'm going to close the ticket. My apologies for the confusions just now.
