### ISSUE TITLE
Unable to access points of polygon object (?)

### ISSUE THREAD

**Issue by parthier** [TheBoneJarmer/TiledCS#28]
I'm not sure if I'm missing something because I'm pretty new to this, but since I don't know where else to ask or contact you I thought I'd open this issue. When I've got an object of type TiledObject there seems to be no way to access the points of the polygon (if it's a polygon). Is that currently not possible or am I missing something?

**Comment by TheBoneJarmer** [comment]
Hi @parthier 

Thank you for reaching out! And for further references, opening an issue is always the best way to go if you are unsure. It is true that polygons are currently unsupported. To be fair, you'd be the first one to talk about it since ages so I honestly completely forgot all about the feature. That said, I'll add support for it of course.

With kind regards,
TheBoneJarmer

**Comment by TheBoneJarmer** [comment]
Hi @parthier 

Support has been added. Changes are in develop now but will publish a release soon. :)

With kind regards,
TheBoneJarmer

**Comment by parthier** [comment]
Wow, that was fast! And thank you a lot for this awesome library.

**Comment by TheBoneJarmer** [comment]
Hey, not a problem at all. Thanks a lot for the kind words! :D
