### ISSUE TITLE
Unit tests and some serialization cleanup

### ISSUE THREAD

**Issue by vpenades** [TheBoneJarmer/TiledCS#29]
Hi, I've been tinkering with the library, and I felt like doing some additions I need.

I've forked the library here: https://github.com/vpenades/TiledCS

And I've did these changes:
- Constrained to C# LangVersion 5 (which is a requirement of MonoGame)
- Added much needed unit tests
- Deserialization code has been simplified a bit (partially forced due to LangVersion 5)
- Added debugger display attributes for easy read
- Some methods can be declared as static

I'm going to keep moving with my fork, but if you wish, I could open a PR now with all those changes.

Also, how's the status of #26 ?  I've seen there's PRs in the works, but not merged yet?

**Comment by TheBoneJarmer** [comment]
Hi @vpenades 

First of all, thanks a lot for the effort you put into this. I have not had the time yet to look at your fork but will do so later. That said, concerning the LangVersion 5 requirement. I am purposely not aiming at any game engine or framework so I can keep it generic.  Because once you start modifications specific for another framework or engine, you won't stop and at a certain point others like to have specific changes for their framework or engine too resulting in a clash and a dirty state of the code. Which I am avoiding at all costs. 

Like you said yourself, you were partially forced to make changes to code that works for everyone else but for you because of a requirement of the game framework that you decided to use. I personally think that is not really healthy, but if the MonoGame devs needed it of course so be it. I can understand though, dotnet changed a lot between the last 3 versions so I am not surprised in the least. lol

It is for such reasons I decided to not modify TiledCS directly but work with what I call an extension structure. So like, instead of making TiledCS work (and if that is possible at all) for all game frameworks and engines, I let others create extension libraries that depend on TiledCS. My good friend and former maintainer of this repo, @delightedcat, once owned a repository where he managed to make TiledCS run with MonoGame for TMX and TSX files. It can be located [here](https://github.com/delightedcat/TiledCS.Extensions.MonoGame). I recommend giving a look if you are in need of loading Tiled maps in MonoGame. Of course you are free to fork your version of TiledCS and modify it to suit your needs.

As for the status of #26, it got closed by the author. I do not know why exactly though although I expect it has to do with our discussion. To be clear, in no way I tried to be rude. But he agreed the code of his PR was a mess and that it was quickly put together because of a gamejam. For that reason I honestly did not know for certain if he really wanted me to merge his changes into develop or if he was just like "yoo maybe this can help". In any case, the support for inifnite layers will come anyway since he has a valid point.

With kind regards,
TheBoneJarmer

**Comment by vpenades** [comment]
Regarding LangVersion 5, this requires a bit of an explanation:

MonoGame is stuck at Net4.5 not only at the framework level, but also at language level (ver 5), the reason is because MonoGame is able to target console platforms, like Nintendo Switch and Playstation.

Apparently, console platforms require AOT compilation, which so far, it's not possible for C# yet, so they developed their own cross compiler called [BRUTE](http://brute.rocks/), which is what you need to write c# code on consoles, And it seems brute is stuck in c# 5

In the monogame forums there's talks about upgrading BRUTE, or completely replacing it with some obscure future AOT compilation brought by Net6... but given the pace of things, I don't think it will be ready anytime soon. Actually, I've been pushing monogame to support newer framewoks/langversions, etc, with little success.

Partially related, I am aware that Unity has its own bag of issues when compiling newer versions of C#, that's why I thought convenient to add that constraint.

Also, I want to clarify this is not my requirement. Actually, because you mentioned in the main readme your aim is game engines like monogame, with no dependencies and so on, I thought it was _your_ requirement!

In practice, it only affected the string concatenation feature:  `$"{this} that" ` needs to be written in the old way `this.ToString() + "that"`.  So it's not like by lowering LangVersion you loose something. Actually, it makes the library much more compatible with compilers other than the official dotnet compiler, so supporting LangVersion 5 can be seen as expanding the compatibility of the library, instead of constraining it to a specific engine.

Regarding the infinite layers, I can live without them for now... but they would greatly simplify my life.

As a last note, right now I've been tasked to develop a game which requires a scrolling game map, which I will be investing heavily on Tiled, either your lib or my own or someone else's, don't really case. I would preffer to support someone else's library because I am already maintaining too much stuff, so if you're happy with what I can offer, then I think we can do some good stuff.

So my contributions would be in line of making the library more compatible and robust, while keeping independent from any engine.

**Comment by delightedcat** [comment]
> MonoGame is stuck at Net4.5 not only at the framework level, but also at language level (ver 5), the reason is because MonoGame is able to target console platforms, like Nintendo Switch and Playstation.

May I ask which version of MonoGame you are running? I remember .NET Framework 4.5 being a requirement for older framework versions ([3.7](https://community.monogame.net/t/monogame-3-7-1/11173) was the last) but since the release of [MonoGame 3.8](https://community.monogame.net/t/monogame-3-8/13312), games are able to run using .NET Core 3.1 and even .NET 5.0. I'm not an expert in terms of console development, though.

I understand your attempt of making TiledCS work with as many framework versions/platforms as possible, but I believe .NET Standard 2.0 has support for quite the range of [.NET versions](https://docs.microsoft.com/en-us/dotnet/standard/net-standard), and with the constant changes to the Tiled API it is quite difficult to stand still and keep on supporting old versions.

Or is your problem solely aimed at the use of BRUTE? Since BRUTE is a closed-source project and none of the maintainers are believed to have access to the source code, it would be very difficult to add a layer of compatibility specifically for this particular tool that didn't get a copyright update [since 2018](http://brute.rocks/).

**Comment by vpenades** [comment]
I'm using MonoGame 3.8 desktop because I'm the maintainer of a long running project... But I'm beginning to hate it because the lack of support.

Si to be clear, if you're happy with supporting latest lang version

**Comment by vpenades** [comment]
, I'm happy to

**Comment by TheBoneJarmer** [comment]
I have had a look at Brute as well and am quite surprised about the state that it currently is in. Like my friend said, it is not only outdated but also, the links to GitHub are all broken. So either the source is lost or closed. And I am guessing not up-to-date too. With other words a total mess. It does not surprise me in any way that there is an ongoing discussion regarding the use of Brute or an alternative.

In any case, I managed to take a quick look at your fork. The unit tests look good and worth adding for sure. Will have to look into it further another day though. But on first sight it looks really good.

**Comment by TheBoneJarmer** [comment]
And as for the whole issue concerning C# 5. If I understand correctly now, Brute does not work with C# versions bigger than 5, right? Because if that is the case I cannot do this. Not just only for reasons mentioned earlier but also in regard to other users. Constraining to a certain version could break versions of Tiled for everyone else.

Don't take me wrong here, I feel for you. I personally don't like MonoGame either because of the stability of the project. Quit with it long time ago. I can only wish you lots of luck with the maintenance of that project that seems like a big burden. I will have to think this through thoroughly first and see what the best way to go is. Since it seems that for non-console targets, TiledCS is fine as it is. But perhaps I need to consider releasing a separate NuGet package just for the sake of this mess. I can only imagine the pain other users are going through as well.

**Comment by TheBoneJarmer** [comment]
> Also, I want to clarify this is not my requirement. Actually, because you mentioned in the main readme your aim is game engines like monogame, with no dependencies and so on, I thought it was _your_ requirement!

Yea sorry 'bout that. I re-read my own README and kinda have to admit that it was not properly formulated. What I meant to say is that TiledCS is aimed at game frameworks and game engines, on a general way. As in, it is not tailored for it but can be used for it using the extension libraries.

**Comment by vpenades** [comment]
> And as for the whole issue concerning C# 5. If I understand correctly now, Brute does not work with C# versions bigger than 5, right?

yes

> Because if that is the case I cannot do this. Not just only for reasons mentioned earlier but also in regard to other users. Constraining to a certain version could break versions of Tiled for everyone else.

No, LangVersion 5 has effects only when compiling TiledCS itself, it does not affect anybody from consuming TiledCS from higher frameworks and LangVersions.

Anyway, I've already removed the LangVersion restriction on my fork, as I said, if it doesn't bother you, it's better to get rid of it

**Comment by vpenades** [comment]
On the infinite grid support, I've read the PR that was cancelled, about the issue of "merging" the grids; I agree trying to merge is a mistake because it would require too much memory.

I think the right solution is to _virtualize_ the access to the map cells.

Consider this interface:

IOrthogonalLayerView
{
    TileInfo GetTile(int x, int y);
}

This interface can be implemented by two accessors:
- a regular layer accessor that simply reads the map data.
- a more advanced accesor that traverses the grids looking for a match.

Any developer using the interface could retrieve an tile at any position, without needing to take care about the underlaying representation.

**Comment by vpenades** [comment]
Okey, in the last commits of my fork, I've refactored the xml serialization code to be much more generic, and also added chunk decoding for infinite maps

**Comment by TheBoneJarmer** [comment]
Hey

I am going to close this issue since it stranded a bit. I have to be honest, I did not look into it further. But I would like to wait with unit testing anyway. To be fair, need to hone my unit test skills for C# a bit further in order to do so properly. Yea I know, shame on me lol.

Concerning the support for infinite layers, I created a separate issue for it so I can use that to focus on it. So if you are interested in that, you should keep an eye on it.

With kind regards,
TheBoneJarmer
