### ISSUE TITLE
Feature Request: Tileset Collision Polygons

### ISSUE THREAD

**Issue by Bryan-Legend** [TheBoneJarmer/TiledCS#31]
Thank you for adding support for object geometry in the last release.

Could you please add support for tile collision geometry? Attached is an example tileset.

Here is what the data looks like:

```
<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.5" tiledversion="1.7.2" name="Basic" tilewidth="32" tileheight="32" tilecount="1024" columns="32">
 <image source="Tileset.png" width="1024" height="1024"/>
 <tile id="0" type="Collapsable"/>
 <tile id="1">
  <objectgroup draworder="index" id="2">
   <object id="1" x="0" y="0" width="32" height="32"/>
   <object id="2" x="0" y="0" width="32" height="32"/>
  </objectgroup>
 </tile>
 <tile id="2" type="Spike"/>
 <tile id="3" type="Collapsable"/>
 <tile id="4">
  <objectgroup draworder="index" id="2">
   <object id="1" x="0" y="0" width="32" height="32"/>
  </objectgroup>
 </tile>
 <tile id="7">
  <objectgroup draworder="index" id="2">
   <object id="1" x="0" y="0">
    <polygon points="0,0 0,32 32,32 32,16"/>
   </object>
  </objectgroup>
 </tile>
 <tile id="8">
  <objectgroup draworder="index" id="2">
   <object id="1" x="0" y="16">
    <polygon points="0,0 0,16 32,16"/>
   </object>
  </objectgroup>
 </tile>
</tileset>
```

[Tileset Collision Example.zip](https://github.com/TheBoneJarmer/TiledCS/files/7681956/Tileset.Collision.Example.zip)

**Comment by lonely-unicorn** [comment]
Hi

I was wondering if this feature is ready now to be added?

Thx

**Comment by TheBoneJarmer** [comment]
Hey

I am sorry for the late reply. Earlier today I finished adding support for this. It will be included with the next major release, which will come soon.

With kind regards,
TheBoneJarmer

**Comment by Bryan-Legend** [comment]
> 

Thank you so much! Perfect timing for me. :)

**Comment by Bryan-Legend** [comment]
I've not looked at how you did this, but could it possibly use a Vector2 class like this: https://docs.microsoft.com/en-us/dotnet/api/system.numerics.vector2?view=net-6.0

**Comment by TheBoneJarmer** [comment]
Gosh. Possible, yes, but I do not think it adds anything of value. If nothing else, it only introduces more problems. The thing is, there are many projects who implement their version of a vector2. Like MonoGame has their version, Unity does so as well and so on. And some of the issues that could appear are:
* Name conflicts since a lot of people use the name _Vector2_.
* Users would have to add an extension method that compares my Vector2 class with theirs
* Users would have to extend their constructors
* Users would have to add mathematical operators since they are not of the same type

Aside of that all, most Vector2 classes come with some extra functionality. Although I would not need that. The Vector2 class would actually become a Vector2 struct since all I would be using it for is merely storage.

**Comment by Bryan-Legend** [comment]
It's pretty easy to convert. I just think it's important to have the right structure.

I think Unity already has converters to the standard System.Numerics.Vector2 struct.

**Comment by TheBoneJarmer** [comment]
Yea okay, but still. The issues I described would still apply for everyone else. And I do not really see any added value by doing so. If would only frustrate others I think due the fact they now have to make a change merely because of someone's preference. It would have been a different case if I would have started out with a Vector2 class or struct.
