### ISSUE TITLE
monogame pipeline

### ISSUE THREAD

**Issue by monogamefan** [TheBoneJarmer/TiledCS#54]
Hi

Could you maybe add a monogame pipeline?
Not esy to find a library for monogame that has a Tiled pipeline

**Comment by monogamefan** [comment]
I just read this:

A huge thanks to DelightedCat who created a MonoGame pipeline. Although the pipeline isn't officially included in this library (as we both agreed to keep it standalone and not engine-based), you can ask help and questions here as DelightedCat is an official maintainer.

Where can I download this pipeline?
I'm very interested!

**Comment by TheBoneJarmer** [comment]
Hey

I am sorry but I am not going to do this. TiledCS is a generic library that does not aim at a specific game framework or engine. And I am also sorry for the confusion caused by that line in the README. DelightedCat is no longer working with MonoGame and has therefore drawn back the project entirely. I asked him if he still has it somewhere but alas. I updated the README in the meantime.

The problem according to him was that it is a hell to maintain it due to MonoGame's lack of good documentation and the limits of the design, making it impossible at some point to do it generic. So for anyone interested in loading TiledCS in MonoGame, it is up to the MonoGame community now to provide such a content pipeline.

With kind regards,
TheBoneJarmer
