### ISSUE TITLE
Let's help other people figure out how to use your library with Monogame.

### ISSUE THREAD

**Issue by nosferatu500** [TheBoneJarmer/TiledCS#62]
Hi! Thank you for this library.

Your example of use case is good, but not really clear in the context of Monogame.

It took a while to figure out how to use it with Monogame until I found this repo:

[https://github.com/Temeez/TiledCS-MonoGame-Example](https://github.com/Temeez/TiledCS-MonoGame-Example)

I think it will be very helpful for other people if you add this link to Readme.md.

**Comment by TheBoneJarmer** [comment]
Hey

You are welcome! I am happy that you like the library. And thanks a lot for the link!! I was hoping somebody would make an example on how to use it in MonoGame sooner or later as I get that question a lot. But I am not using MonoGame at all so I would not know how to. Therefore I must always decline adding support for MonoGame directly in TiledCS.

Will contact the author and request permission to add his repo url to my readme. Because despite the repo being public, adding a link to his repo would pressure him to keep the whole thing up-to-date and functional and give the idea  to the outer world that I say "hey, using monogame? Go for this repo". Not sure if the author wishes for such obligations.

With kind regards,
TheBoneJarmer

**Comment by TheBoneJarmer** [comment]
Hey

I just contacted Temeez and he already replied back. It was a good idea for me to contact him because it turns out he is indeed not actively working with C# or MonoGame for that matter. So he wont update the repo anymore. That said, he gave me permission to add his link anyway so I will add it.

With kind regards,
TheBoneJarmer

**Comment by evilkomododragon** [comment]
@nosferatu500 : You can use monogame.extended to have a very easy to use Tiled library for monogame, including content pipeline for Tiled

**Comment by TheBoneJarmer** [comment]
Hello Jessica or Lisa or whatever your real name is. Please do not advert other Tiled libraries here just because you did not get your way last time. Thanks.

**Comment by TheBoneJarmer** [comment]
There, link has been added. When I merge develop into main, the readme changes will be available there too.
