### ISSUE TITLE
use dictionaries instead of arrays for properties

### ISSUE THREAD

**Issue by BBQGiraffe** [TheBoneJarmer/TiledCS#84]
getting specific items from a TiledProperty array is tedious, it would be much more efficient if properties were in a string indexed dictionary rather than an array

**Comment by TheBoneJarmer** [comment]
Hey @BBQGiraffe 

Thanks for the suggestion. Unfortunately, I can't do it. Properties in Tiled are made up of tree parts. These are `name`, `type` and `value`. A dictionary is only useful for the _name_  and _value_ part. But I think the type is important too since Tiled saves the value as a string in the XML.

With kind regards,
TheBoneJarmer
