### ISSUE TITLE
Issues with objects that belong to tiles

### ISSUE THREAD

**Issue by Frankfires** [TheBoneJarmer/TiledCS#88]
### Retrieving `Object.type` from a tile's objects returns a blank string, I am able to retrieve x/y/width/height which works out for points and rectangles because you can identify the difference between them by checking if width/height is 0. For ellipses and polygons though I'm afraid it's impossible to check if the object is one of those two  
![image](https://user-images.githubusercontent.com/67832033/186728029-4340101c-8e99-430c-a5c2-f466218b0a56.png)
![image](https://user-images.githubusercontent.com/67832033/186727978-d1a28938-d903-4e95-89c5-afc07321eb0c.png)
![image](https://user-images.githubusercontent.com/67832033/186732368-f7fdc286-49d5-4cff-a21d-22ed01b251df.png)
![image](https://user-images.githubusercontent.com/67832033/186732392-b716659c-6af2-4ffc-9468-a58206b53664.png)

### Also, tiles without any objects aren't included in `TiledTileSet`s, adding at least an object to each tile will resolve this error. Don't know if this intentional or not, but I think tiles without objects should still be included in `TiledTileSet`s for easing the process of making tiles without collision
![image](https://user-images.githubusercontent.com/67832033/186734267-dbfec8fe-4b4f-4f0b-8f20-0ad5a46a9a59.png)
![image](https://user-images.githubusercontent.com/67832033/186734254-2f8a6da9-52db-4008-8119-1588e3bdb4fb.png)
![image](https://user-images.githubusercontent.com/67832033/186734863-aadbdc69-0fc0-4927-86e8-fb9988c79541.png)
![image](https://user-images.githubusercontent.com/67832033/186734554-2ab82f34-05c4-4a3c-9ec5-9ac5ef8ee392.png)

**Comment by Frankfires** [comment]
### UPDATE: it appears that I've forgot to subtract my `TileID` variable by 1 like the half brain celled sack of flesh I am, the out of bounds exception is my fault 🤡

**Comment by TheBoneJarmer** [comment]
Hey @Frankfires

Concerning your issue with the type field. This works as intended. The `type` field is empty I believe because its default is a rectangle.  When you use a tile as object the `type` field is empty too but the `gid` field is set. And in case of a point, polygon or ellipse, the fields `polygon`, `point` and `ellipse` are set respectively. To be honest I don't know for certain when it does get filled. But Tiled was designed this way so I just respect it. But when I talk to Björn I will ask him if he could elaborate on it further. 

As for the issue with the `TiledTileset.Tiles` property, Tiled only saves tiles which contains data like animations or properties. So they only serve as a data container for a specific tile rather than the tile itself. This is how Tiled was designed and thus TiledCS only loads what it can find. I could fill up the array with tiles that were not defined in the tileset but than the whole array could become really big and I am not certain that is desirable for those with many tilesets.

I hope you understand and if you have questions, shoot!

With kind regards,
TheBoneJarmer

**Comment by Frankfires** [comment]
Aha I got it makes sense now ty! 👍
