### ISSUE TITLE
Feature Request: Template Support

### ISSUE THREAD

**Issue by TheBigPrince** [TheBoneJarmer/TiledCS#89]
I'm fairly new to using TiledCS and Tiled. Currently using it with Monogame and it has saved me a tonne of work so thanks for that!

If it's not already on the agenda, I would love to see support for Tiled Templates. Using templates can save a bunch a time in Tiled so it would be a very welcome addition. 

Currently when I cycle through objects in a layer, if that object was created from a tiled template, all values other than id and position are null. 

![image](https://user-images.githubusercontent.com/20147776/186813151-a5339405-17f7-465d-be41-cd79b9f35d8c.png)

I think it would be useful if the data from the template was populated into the object and then overriden if the data was changed on the object instance itself.

For example the properties of template 'PlayerSpawn.tx':
![image](https://user-images.githubusercontent.com/20147776/186813573-e4f2b586-adeb-4f15-9cfb-18d04f6fae51.png)

and the properties of the object instance created from the template:
![image](https://user-images.githubusercontent.com/20147776/186813923-f6a64522-f1c1-406b-98e1-f32d18a15326.png)

I would hope to get an object that had the all the template data and the changed object data, so in the case above:

ID: 19
Name: Player Spawn Instanced
X: 512.00
Y: 800.00

**Comment by TheBigPrince** [comment]
and I just realised that you can select the "Detach Templates" option under Preferences/Export Options in Tiled, then re-export your map to bypass this issue completely. 

![image](https://user-images.githubusercontent.com/20147776/186828524-8e04923c-5bd3-4b0f-9414-b05696215740.png)

Might be worth adding that to the Readme so people new to Tiled & TiledCS (like me) don't stumble into this issue. 

Closing this because this option is fine for me, and again thank you for your work on this!

**Comment by TheBoneJarmer** [comment]
Hey @TheBigPrince 

At this moment there is no template support and to be fair it was not on the agenda either. However! Tiled happens to come with new features over time and this was one that did not existed at the time I started with TiledCS. And truth to be told, I never used them before so it would have to dive a bit deeper in the matter.

That said, it is nice to know it can be bypassed. And so far templates only seemed interesting for well, within the Tiled editor itself. Not so much for exporting. I personally also think that would complicate things. Which is why I am fairly certain Björn added such export option. So I think I will update the README for now and decide later about supporting this feature or not.

In any case, thanks for sharing those screenshots and info! Because of your clear explanation it is most likely I will simply link this issue in the README rather than explaining it all by myself.

With kind regards,
TheBoneJarmer
